FROM node:10
# Create app directory
WORKDIR /usr/share/nginx/html
# Install app dependencies
COPY . .

RUN npm install --silent
# Copy app source code
COPY . .

#Expose port and start application
EXPOSE 3000
CMD ["npm", "start"]